[package]
name = "brain"
version = "0.1.0"
edition = "2021"
description = "A post-transformer developmental AI architecture"
authors = ["Brain Team"]
license-file = "LICENSE"

[dependencies]
# Linear algebra
nalgebra = "0.32"

# Random number generation
rand = "0.8"

# Serialization for saving models and data
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# CLI and logging
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4"

# Async runtime for potential future features
tokio = { version = "1.0", features = ["full"] }

# File I/O and utilities
anyhow = "1.0"
thiserror = "1.0"

# Memory Module Dependencies (Task 3) - Lightweight approach
# SQLite for episodic memory storage (lighter than DuckDB)
rusqlite = { version = "0.30", features = ["bundled"] }

# Simple vector operations for semantic memory
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
criterion = "0.5"
tempfile = "3.10"

[lib]
name = "brain"
path = "src/lib.rs"

[[bin]]
name = "brain-cli"
path = "src/main.rs" 