[book]
authors = ["Brain AI Development Team"]
language = "en"
multilingual = false
src = "src"
title = "Brain AI Documentation"
description = "Complete documentation for the Brain AI cognitive architecture system"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
git-repository-url = "https://github.com/your-org/brain-ai"
edit-url-template = "https://github.com/your-org/brain-ai/edit/main/docs/{path}"
theme = "theme"
no-section-label = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true
page-break = true



[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true
